name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Run every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Check
        run: curl -s ${{ secrets.RENDER_EXTERNAL_URL }} || true
        env:
          RENDER_EXTERNAL_URL: ${{ secrets.RENDER_EXTERNAL_URL }}
