name: Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Check
        run: curl -v https://telegram-bot-vfnd.onrender.com || echo "Ping failed with status $?"
        env:
          RENDER_EXTERNAL_URL: ${{ secrets.RENDER_EXTERNAL_URL }}
